#ifndef __MCPE_ENTITY_H
#define __MCPE_ENTITY_H

struct Level;
struct BlockSource;

struct Entity
{
	char filler[64];
	Level* level; // 64
	char filler2[104]; // 72
	BlockSource* region; // 176
};

/*
.data.rel.ro:01B68EA8                 DCD _ZN6Entity15reloadHardcodedENS_20InitializationMethodERK20VariantParameterList+1 ; Entity::reloadHardcoded(Entity::InitializationMethod,VariantParameterList const&)
.data.rel.ro:01B68EAC                 DCD _ZN6Entity21reloadHardcodedClientENS_20InitializationMethodERK20VariantParameterList+1 ; Entity::reloadHardcodedClient(Entity::InitializationMethod,VariantParameterList const&)
.data.rel.ro:01B68EB0                 DCD _ZN6Entity16reloadComponentsENS_20InitializationMethodERK20VariantParameterList+1 ; Entity::reloadComponents(Entity::InitializationMethod,VariantParameterList const&)
.data.rel.ro:01B68EB4                 DCD _ZNK6Entity12hasComponentERKSs+1 ; Entity::hasComponent(std::string const&)
.data.rel.ro:01B68EB8                 DCD _ZN6EntityD2Ev+1    ; Entity::~Entity()
.data.rel.ro:01B68EBC                 DCD _ZN6EntityD0Ev+1    ; Entity::~Entity()
.data.rel.ro:01B68EC0                 DCD _ZN6Entity5resetEv+1 ; Entity::reset(void)
.data.rel.ro:01B68EC4                 DCD _ZN6Entity18getOwnerEntityTypeEv+1 ; Entity::getOwnerEntityType(void)
.data.rel.ro:01B68EC8                 DCD _ZN6Entity6removeEv+1 ; Entity::remove(void)
.data.rel.ro:01B68ECC                 DCD _ZN6Entity6setPosERK4Vec3+1 ; Entity::setPos(Vec3 const&)
.data.rel.ro:01B68ED0                 DCD _ZNK6Entity6getPosEv+1 ; Entity::getPos(void)
.data.rel.ro:01B68ED4                 DCD _ZNK6Entity9getPosOldEv+1 ; Entity::getPosOld(void)
.data.rel.ro:01B68ED8                 DCD _ZNK6Entity18getPosExtrapolatedEf+1 ; Entity::getPosExtrapolated(float)
.data.rel.ro:01B68EDC                 DCD _ZNK6Entity11getVelocityEv+1 ; Entity::getVelocity(void)
.data.rel.ro:01B68EE0                 DCD _ZN6Entity4moveERK4Vec3+1 ; Entity::move(Vec3 const&)
.data.rel.ro:01B68EE4                 DCD _ZN6Entity20checkBlockCollisionsERK4AABB+1 ; Entity::checkBlockCollisions(AABB const&)
.data.rel.ro:01B68EE8                 DCD _ZN6Entity20checkBlockCollisionsEv+1 ; Entity::checkBlockCollisions(void)
.data.rel.ro:01B68EEC                 DCD _ZN6Entity6canFlyEv+1 ; Entity::canFly(void)
.data.rel.ro:01B68EF0                 DCD _ZN6Entity12moveRelativeEfff+1 ; Entity::moveRelative(float,float,float)
.data.rel.ro:01B68EF4                 DCD _ZN6Entity10teleportToERK4Vec3+1 ; Entity::teleportTo(Vec3 const&)
.data.rel.ro:01B68EF8                 DCD _ZN6Entity6lerpToERK4Vec3RK4Vec2i+1 ; Entity::lerpTo(Vec3 const&,Vec2 const&,int)
.data.rel.ro:01B68EFC                 DCD _ZN6Entity10lerpMotionERK4Vec3+1 ; Entity::lerpMotion(Vec3 const&)
.data.rel.ro:01B68F00                 DCD _ZN6Entity4turnERK4Vec2b+1 ; Entity::turn(Vec2 const&,bool)
.data.rel.ro:01B68F04                 DCD _ZN6Entity15interpolateTurnERK4Vec2+1 ; Entity::interpolateTurn(Vec2 const&)
.data.rel.ro:01B68F08                 DCD _ZN6Entity12getAddPacketEv+1 ; Entity::getAddPacket(void)
.data.rel.ro:01B68F0C                 DCD _ZN6Entity10normalTickEv+1 ; Entity::normalTick(void)
.data.rel.ro:01B68F10                 DCD _ZN6Entity8baseTickEv+1 ; Entity::baseTick(void)
.data.rel.ro:01B68F14                 DCD _ZN6Entity8rideTickEv+1 ; Entity::rideTick(void)
.data.rel.ro:01B68F18                 DCD _ZNK6Entity13positionRiderERS_+1 ; Entity::positionRider(Entity&)
.data.rel.ro:01B68F1C                 DCD _ZN6Entity15getRidingHeightEv+1 ; Entity::getRidingHeight(void)
.data.rel.ro:01B68F20                 DCD _ZN6Entity11startRidingERS_+1 ; Entity::startRiding(Entity&)
.data.rel.ro:01B68F24                 DCD _ZN6Entity8addRiderERS_+1 ; Entity::addRider(Entity&)
.data.rel.ro:01B68F28                 DCD _ZN6Entity17flagRiderToRemoveERS_+1 ; Entity::flagRiderToRemove(Entity&)
.data.rel.ro:01B68F2C                 DCD _ZN6Entity10intersectsERK4Vec3S2_+1 ; Entity::intersects(Vec3 const&,Vec3 const&)
.data.rel.ro:01B68F30                 DCD _ZN6Entity6isFreeERK4Vec3f+1 ; Entity::isFree(Vec3 const&,float)
.data.rel.ro:01B68F34                 DCD _ZN6Entity6isFreeERK4Vec3+1 ; Entity::isFree(Vec3 const&)
.data.rel.ro:01B68F38                 DCD _ZNK6Entity8isInWallEv+1 ; Entity::isInWall(void)
.data.rel.ro:01B68F3C                 DCD _ZNK6Entity11isInvisibleEv+1 ; Entity::isInvisible(void)
.data.rel.ro:01B68F40                 DCD _ZN6Entity14canShowNameTagEv+1 ; Entity::canShowNameTag(void)
.data.rel.ro:01B68F44                 DCD _ZN6Entity17setNameTagVisibleEb+1 ; Entity::setNameTagVisible(bool)
.data.rel.ro:01B68F48                 DCD _ZNK6Entity10getNameTagEv+1 ; Entity::getNameTag(void)
.data.rel.ro:01B68F4C                 DCD _ZNK6Entity19getFormattedNameTagEv+1 ; Entity::getFormattedNameTag(void)
.data.rel.ro:01B68F50                 DCD _ZN6Entity10setNameTagERKSs+1 ; Entity::setNameTag(std::string const&)
.data.rel.ro:01B68F54                 DCD _ZNK6Entity9isInWaterEv+1 ; Entity::isInWater(void)
.data.rel.ro:01B68F58                 DCD _ZN6Entity15isInWaterOrRainEv+1 ; Entity::isInWaterOrRain(void)
.data.rel.ro:01B68F5C                 DCD _ZN6Entity8isInLavaEv+1 ; Entity::isInLava(void)
.data.rel.ro:01B68F60                 DCD _ZNK6Entity13isUnderLiquidE12MaterialType+1 ; Entity::isUnderLiquid(MaterialType)
.data.rel.ro:01B68F64                 DCD _ZN6Entity14makeStuckInWebEv+1 ; Entity::makeStuckInWeb(void)
.data.rel.ro:01B68F68                 DCD _ZNK6Entity13getHeadHeightEv+1 ; Entity::getHeadHeight(void)
.data.rel.ro:01B68F6C                 DCD _ZN6Entity19getShadowHeightOffsEv+1 ; Entity::getShadowHeightOffs(void)
.data.rel.ro:01B68F70                 DCD _ZNK6Entity15getShadowRadiusEv+1 ; Entity::getShadowRadius(void)
.data.rel.ro:01B68F74                 DCD _ZN6Entity9isSwimmerEv+1 ; Entity::isSwimmer(void)
.data.rel.ro:01B68F78                 DCD _ZN6Entity15canSeeInvisibleEv+1 ; Entity::canSeeInvisible(void)
.data.rel.ro:01B68F7C                 DCD _ZN6Entity8isSkyLitEf+1 ; Entity::isSkyLit(float)
.data.rel.ro:01B68F80                 DCD _ZNK6Entity13getBrightnessEf+1 ; Entity::getBrightness(float)
.data.rel.ro:01B68F84                 DCD _ZN6Entity22interactPreventDefaultEv+1 ; Entity::interactPreventDefault(void)
.data.rel.ro:01B68F88                 DCD _ZN6Entity11playerTouchER6Player+1 ; Entity::playerTouch(Player &)
.data.rel.ro:01B68F8C                 DCD _ZN6Entity4pushERS_b+1 ; Entity::push(Entity&,bool)
.data.rel.ro:01B68F90                 DCD _ZN6Entity4pushERK4Vec3+1 ; Entity::push(Vec3 const&)
.data.rel.ro:01B68F94                 DCD _ZNK6Entity10isImmobileEv+1 ; Entity::isImmobile(void)
.data.rel.ro:01B68F98                 DCD _ZN6Entity8isSilentEv+1 ; Entity::isSilent(void)
.data.rel.ro:01B68F9C                 DCD _ZN6Entity10isPickableEv+1 ; Entity::isPickable(void)
.data.rel.ro:01B68FA0                 DCD _ZNK6Entity10isFishableEv+1 ; Entity::isFishable(void)
.data.rel.ro:01B68FA4                 DCD _ZNK6Entity10isPushableEv+1 ; Entity::isPushable(void)
.data.rel.ro:01B68FA8                 DCD _ZNK6Entity18isPushableByPistonEv+1 ; Entity::isPushableByPiston(void)
.data.rel.ro:01B68FAC                 DCD _ZN6Entity11isShootableEv+1 ; Entity::isShootable(void)
.data.rel.ro:01B68FB0                 DCD _ZNK6Entity10isSneakingEv+1 ; Entity::isSneaking(void)
.data.rel.ro:01B68FB4                 DCD _ZNK6Entity7isAliveEv+1 ; Entity::isAlive(void)
.data.rel.ro:01B68FB8                 DCD _ZNK6Entity8isOnFireEv+1 ; Entity::isOnFire(void)
.data.rel.ro:01B68FBC                 DCD _ZN6Entity21isCreativeModeAllowedEv+1 ; Entity::isCreativeModeAllowed(void)
.data.rel.ro:01B68FC0                 DCD _ZNK6Entity12isSurfaceMobEv+1 ; Entity::isSurfaceMob(void)
.data.rel.ro:01B68FC4                 DCD _ZN6Entity9setTargetEPS_+1 ; Entity::setTarget(Entity*)
.data.rel.ro:01B68FC8                 DCD _ZN6Entity8setOwnerE14EntityUniqueID+1 ; Entity::setOwner(EntityUniqueID)
.data.rel.ro:01B68FCC                 DCD _ZN6Entity10setSittingEb+1 ; Entity::setSitting(bool)
.data.rel.ro:01B68FD0                 DCD _ZN6Entity6onTameEv+1 ; Entity::onTame(void)
.data.rel.ro:01B68FD4                 DCD _ZN6Entity12onFailedTameEv+1 ; Entity::onFailedTame(void)
.data.rel.ro:01B68FD8                 DCD _ZN6Entity6onMateER3Mob+1 ; Entity::onMate(Mob &)
.data.rel.ro:01B68FDC                 DCD _ZN6Entity4hurtERK18EntityDamageSourceibb+1 ; Entity::hurt(EntityDamageSource const&,int,bool,bool)
.data.rel.ro:01B68FE0                 DCD _ZN6Entity11animateHurtEv+1 ; Entity::animateHurt(void)
.data.rel.ro:01B68FE4                 DCD _ZN6Entity10doFireHurtEi+1 ; Entity::doFireHurt(int)
.data.rel.ro:01B68FE8                 DCD _ZN6Entity14onLightningHitEv+1 ; Entity::onLightningHit(void)
.data.rel.ro:01B68FEC                 DCD _ZN6Entity15onBounceStartedERK8BlockPosRK9FullBlock+1 ; Entity::onBounceStarted(BlockPos const&,FullBlock const&)
.data.rel.ro:01B68FF0                 DCD _ZN6Entity17handleEntityEventE11EntityEventi+1 ; Entity::handleEntityEvent(EntityEvent,int)
.data.rel.ro:01B68FF4                 DCD _ZN6Entity13getPickRadiusEv+1 ; Entity::getPickRadius(void)
.data.rel.ro:01B68FF8                 DCD _ZN6Entity15spawnAtLocationEii+1 ; Entity::spawnAtLocation(int,int)
.data.rel.ro:01B68FFC                 DCD _ZN6Entity15spawnAtLocationEiif+1 ; Entity::spawnAtLocation(int,int,float)
.data.rel.ro:01B69000                 DCD _ZN6Entity15spawnAtLocationE9FullBlocki+1 ; Entity::spawnAtLocation(FullBlock,int)
.data.rel.ro:01B69004                 DCD _ZN6Entity15spawnAtLocationE9FullBlockif+1 ; Entity::spawnAtLocation(FullBlock,int,float)
.data.rel.ro:01B69008                 DCD _ZN6Entity15spawnAtLocationERK12ItemInstancef+1 ; Entity::spawnAtLocation(ItemInstance const&,float)
.data.rel.ro:01B6900C                 DCD _ZN6Entity6killedEPS_+1 ; Entity::killed(Entity*)
.data.rel.ro:01B69010                 DCD _ZN6Entity14awardKillScoreERS_i+1 ; Entity::awardKillScore(Entity&,int)
.data.rel.ro:01B69014                 DCD _ZN6Entity15setEquippedSlotE9ArmorSlotii+1 ; Entity::setEquippedSlot(ArmorSlot,int,int)
.data.rel.ro:01B69018                 DCD _ZN6Entity15setEquippedSlotE9ArmorSlotRK12ItemInstance+1 ; Entity::setEquippedSlot(ArmorSlot,ItemInstance const&)
.data.rel.ro:01B6901C                 DCD _ZN6Entity4saveER11CompoundTag+1 ; Entity::save(CompoundTag &)
.data.rel.ro:01B69020                 DCD _ZN6Entity13saveWithoutIdER11CompoundTag+1 ; Entity::saveWithoutId(CompoundTag &)
.data.rel.ro:01B69024                 DCD _ZN6Entity4loadERK11CompoundTag+1 ; Entity::load(CompoundTag const&)
.data.rel.ro:01B69028                 DCD _ZN6Entity9loadLinksERK11CompoundTagRSt6vectorI10EntityLinkSaIS4_EE+1 ; Entity::loadLinks(CompoundTag const&,std::vector<EntityLink,std::allocator<EntityLink>> &)
.data.rel.ro:01B6902C                 DCD __cxa_pure_virtual+1
.data.rel.ro:01B69030                 DCD _ZN6Entity26acceptClientsideEntityDataER6PlayerRK19SetEntityDataPacket+1 ; Entity::acceptClientsideEntityData(Player &,SetEntityDataPacket const&)
.data.rel.ro:01B69034                 DCD _ZN6Entity19queryEntityRendererEv+1 ; Entity::queryEntityRenderer(void)
.data.rel.ro:01B69038                 DCD _ZN6Entity17getSourceUniqueIDEv+1 ; Entity::getSourceUniqueID(void)
.data.rel.ro:01B6903C                 DCD _ZN6Entity9setOnFireEi+1 ; Entity::setOnFire(int)
.data.rel.ro:01B69040                 DCD _ZNK6Entity18getHandleWaterAABBEv+1 ; Entity::getHandleWaterAABB(void)
.data.rel.ro:01B69044                 DCD _ZN6Entity18handleInsidePortalERK8BlockPos+1 ; Entity::handleInsidePortal(BlockPos const&)
.data.rel.ro:01B69048                 DCD _ZNK6Entity17getPortalCooldownEv+1 ; Entity::getPortalCooldown(void)
.data.rel.ro:01B6904C                 DCD _ZNK6Entity17getPortalWaitTimeEv+1 ; Entity::getPortalWaitTime(void)
.data.rel.ro:01B69050                 DCD _ZNK6Entity14getDimensionIdEv+1 ; Entity::getDimensionId(void)
.data.rel.ro:01B69054                 DCD _ZN6Entity15changeDimensionE11DimensionId+1 ; Entity::changeDimension(DimensionId)
.data.rel.ro:01B69058                 DCD _ZN6Entity15changeDimensionERK21ChangeDimensionPacket+1 ; Entity::changeDimension(ChangeDimensionPacket const&)
.data.rel.ro:01B6905C                 DCD _ZNK6Entity20getControllingPlayerEv+1 ; Entity::getControllingPlayer(void)
.data.rel.ro:01B69060                 DCD _ZN6Entity15checkFallDamageEfb+1 ; Entity::checkFallDamage(float,bool)
.data.rel.ro:01B69064                 DCD _ZN6Entity15causeFallDamageEf+1 ; Entity::causeFallDamage(float)
.data.rel.ro:01B69068                 DCD _ZN6Entity21playSynchronizedSoundE15LevelSoundEventRK4Vec3ib+1 ; Entity::playSynchronizedSound(LevelSoundEvent,Vec3 const&,int,bool)
.data.rel.ro:01B6906C                 DCD _ZN6Entity19onSynchedDataUpdateEi+1 ; Entity::onSynchedDataUpdate(int)
.data.rel.ro:01B69070                 DCD _ZNK6Entity11canAddRiderERS_+1 ; Entity::canAddRider(Entity&)
.data.rel.ro:01B69074                 DCD _ZN6Entity12canBeLeashedEv+1 ; Entity::canBeLeashed(void)
.data.rel.ro:01B69078                 DCD _ZN6Entity15isLeashableTypeEv+1 ; Entity::isLeashableType(void)
.data.rel.ro:01B6907C                 DCD _ZN6Entity9tickLeashEv+1 ; Entity::tickLeash(void)
.data.rel.ro:01B69080                 DCD _ZNK6Entity12getEyeHeightEv+1 ; Entity::getEyeHeight(void)
.data.rel.ro:01B69084                 DCD _ZN6Entity24sendMotionPacketIfNeededEv+1 ; Entity::sendMotionPacketIfNeeded(void)
.data.rel.ro:01B69088                 DCD _ZN6Entity10stopRidingEbb+1 ; Entity::stopRiding(bool,bool)
.data.rel.ro:01B6908C                 DCD _ZNK6Entity14buildDebugInfoERSs+1 ; Entity::buildDebugInfo(std::string &)
.data.rel.ro:01B69090                 DCD _ZN6Entity22openContainerComponentER6Player+1 ; Entity::openContainerComponent(Player &)
.data.rel.ro:01B69094                 DCD _ZNK6Entity15hasOutputSignalEa+1 ; Entity::hasOutputSignal(signed char)
.data.rel.ro:01B69098                 DCD _ZNK6Entity15getOutputSignalEv+1 ; Entity::getOutputSignal(void)
.data.rel.ro:01B6909C                 DCD _ZN6Entity12getDebugTextERSt6vectorISsSaISsEE+1 ; Entity::getDebugText(std::vector<std::string,std::allocator<std::string>> &)
.data.rel.ro:01B690A0                 DCD _ZN6Entity17startSeenByPlayerER6Player+1 ; Entity::startSeenByPlayer(Player &)
.data.rel.ro:01B690A4                 DCD _ZN6Entity16stopSeenByPlayerER6Player+1 ; Entity::stopSeenByPlayer(Player &)
.data.rel.ro:01B690A8                 DCD _ZN6Entity24getMapDecorationRotationEv+1 ; Entity::getMapDecorationRotation(void)
.data.rel.ro:01B690AC                 DCD _ZN6Entity26getRiderDecorationRotationER6Player+1 ; Entity::getRiderDecorationRotation(Player &)
.data.rel.ro:01B690B0                 DCD _ZNK6Entity15canDestroyBlockER5Block+1 ; Entity::canDestroyBlock(Block &)
.data.rel.ro:01B690B4                 DCD _ZN6Entity11setAuxValueEi+1 ; Entity::setAuxValue(int)
.data.rel.ro:01B690B8                 DCD _ZN6Entity7setSizeEff+1 ; Entity::setSize(float,float)
.data.rel.ro:01B690BC                 DCD _ZN6Entity6setPosERK9EntityPos+1 ; Entity::setPos(EntityPos const&)
.data.rel.ro:01B690C0                 DCD _ZN6Entity10outOfWorldEv+1 ; Entity::outOfWorld(void)
.data.rel.ro:01B690C4                 DCD _ZN6Entity8markHurtEv+1 ; Entity::markHurt(void)
.data.rel.ro:01B690C8                 DCD _ZN6Entity8lavaHurtEv+1 ; Entity::lavaHurt(void)
.data.rel.ro:01B690CC                 DCD _ZN6Entity22readAdditionalSaveDataERK11CompoundTag+1 ; Entity::readAdditionalSaveData(CompoundTag const&)
.data.rel.ro:01B690D0                 DCD _ZN6Entity21addAdditionalSaveDataER11CompoundTag+1 ; Entity::addAdditionalSaveData(CompoundTag &)
.data.rel.ro:01B690D4                 DCD _ZN6Entity14_playStepSoundERK8BlockPosi+1 ; Entity::_playStepSound(BlockPos const&,int)
.data.rel.ro:01B690D8                 DCD _ZN6Entity17checkInsideBlocksEf+1 ; Entity::checkInsideBlocks(float)
.data.rel.ro:01B690DC                 DCD _ZN6Entity15pushOutOfBlocksERK4Vec3+1 ; Entity::pushOutOfBlocks(Vec3 const&)
.data.rel.ro:01B690E0                 DCD _ZN6Entity16updateWaterStateEv+1 ; Entity::updateWaterState(void)
.data.rel.ro:01B690E4                 DCD _ZN6Entity19doWaterSplashEffectEv+1 ; Entity::doWaterSplashEffect(void)
.data.rel.ro:01B690E8                 DCD _ZN6Entity17updateInsideBlockEv+1 ; Entity::updateInsideBlock(void)
.data.rel.ro:01B690EC                 DCD _ZN6Entity16onBlockCollisionEi+1 ; Entity::onBlockCollision(int)
.data.rel.ro:01B690F0                 DCD _ZNK6Entity12getLootTableEv+1 ; Entity::getLootTable(void)
.data.rel.ro:01B690F4                 DCD _ZNK6Entity19getDefaultLootTableEv+1 ; Entity::getDefaultLootTable(void)
.data.rel.ro:01B690F8                 DCD _ZN6Entity12_removeRiderERS_b+1 ; Entity::_removeRider(Entity&,bool)*/

#endif
